import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useOonApi } from "@oondemand/oon-core-front/hooks";
import { Badge, Button, Card, Empty, Field, Modal, Notice, Page, errorMessage, toneFor } from "../components/Ui";
import type { ConnectionConfig, Paged, Partner } from "../types";
export function PartnersPage() {
  const { http } = useOonApi(); const [connections, setConnections] = useState<ConnectionConfig[]>([]); const [connectionId, setConnectionId] = useState(""); const [query, setQuery] = useState(""); const [data, setData] = useState<Paged<Partner> | null>(null); const [showForm, setShowForm] = useState(false); const [notice, setNotice] = useState<{ tone: "success" | "error"; text: string } | null>(null);
  const [form, setForm] = useState({ legalName: "", tradeName: "", document: "", email: "", phone: "", isCustomer: true, isSupplier: false });
  const loadConnections = useCallback(async () => { const rows = (await http.get<{ items: ConnectionConfig[] }>("/cadastros/connections")).data.items; setConnections(rows); setConnectionId(current => current || rows[0]?.connectionId || ""); }, [http]);
  const load = useCallback(async () => { if (!connectionId) return; const params = new URLSearchParams({ connectionId, query, page: "1", pageSize: "50" }); setData((await http.get<Paged<Partner>>(`/cadastros/entities/partners?${params}`)).data); }, [connectionId, http, query]);
  useEffect(() => { void loadConnections().catch(reason => setNotice({ tone: "error", text: errorMessage(reason) })); }, [loadConnections]); useEffect(() => { void load().catch(reason => setNotice({ tone: "error", text: errorMessage(reason) })); }, [load]);
  async function save(event: FormEvent) { event.preventDefault(); try { const key = crypto.randomUUID(); await http.post("/cadastros/entities/partners", { connectionId, ...form }, { headers: { "Idempotency-Key": key } }); setShowForm(false); setForm({ legalName: "", tradeName: "", document: "", email: "", phone: "", isCustomer: true, isSupplier: false }); await load(); setNotice({ tone: "success", text: "Cadastro enviado ao Omie e projeção reconciliada." }); } catch (reason) { setNotice({ tone: "error", text: errorMessage(reason) }); } }
  return <Page eyebrow="Clientes e fornecedores" title="Pessoas certas, na base certa" description="Busca rápida, papéis claros e origem Omie sempre visível." actions={<Button disabled={!connectionId} onClick={() => setShowForm(true)}>Novo cadastro</Button>}>
    {notice && <Notice tone={notice.tone}>{notice.text}</Notice>}
    <Card><div className="oon-toolbar"><Field label="Base"><select value={connectionId} onChange={e => setConnectionId(e.target.value)}>{connections.map(row => <option key={row.connectionId}>{row.connectionId}</option>)}</select></Field><Field label="Pesquisar"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Nome, documento ou e-mail" /></Field></div></Card>
    <Modal open={showForm} onClose={() => setShowForm(false)} title="Novo cliente ou fornecedor" description="O nome/razão social é obrigatório. Dados fiscais adicionais podem ser completados no detalhe."><form onSubmit={save}><div className="oon-form-grid"><Field label="Razão social / nome"><input required maxLength={60} value={form.legalName} onChange={e => setForm({ ...form, legalName: e.target.value })} /></Field><Field label="Nome fantasia"><input maxLength={100} value={form.tradeName} onChange={e => setForm({ ...form, tradeName: e.target.value })} /></Field><Field label="CPF/CNPJ"><input value={form.document} onChange={e => setForm({ ...form, document: e.target.value })} /></Field><Field label="E-mail"><input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></Field><Field label="Telefone"><input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} /></Field><div className="oon-actions"><label><input type="checkbox" checked={form.isCustomer} onChange={e => setForm({ ...form, isCustomer: e.target.checked })} /> Cliente</label><label><input type="checkbox" checked={form.isSupplier} onChange={e => setForm({ ...form, isSupplier: e.target.checked })} /> Fornecedor</label></div></div><div className="oon-actions"><Button type="submit">Salvar no Omie</Button><Button type="button" variant="secondary" onClick={() => setShowForm(false)}>Cancelar</Button></div></form></Modal>
    <Card title="Cadastros encontrados" description={data ? `${data.total} registro(s)` : "Carregando…"}>{!data?.items.length ? <Empty title="Nenhum cadastro encontrado" description="Sincronize a base ou revise os filtros." /> : <div className="oon-list">{data.items.map(row => <article className="oon-list-item" key={row._id}><div><strong>{row.tradeName || row.legalName}</strong><small>{row.legalName} • {row.documentMasked || "Documento não informado"}</small><small>{row.email || row.phone || "Sem contato"} • base {row.omieConnectionId}</small></div><div><small>Papel</small><div className="oon-actions">{row.isCustomer && <Badge>Cliente</Badge>}{row.isSupplier && <Badge>Fornecedor</Badge>}</div></div><div><small>Sincronização</small><Badge tone={toneFor(row.syncState)}>{row.syncState}</Badge></div><small>{row.syncedAt ? new Date(row.syncedAt).toLocaleString("pt-BR") : "Pendente"}</small></article>)}</div>}</Card>
  </Page>;
}
