import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useOonApi } from "@oondemand/oon-core-front/hooks";
import { Badge, Button, Card, Empty, Field, Notice, Page, errorMessage, toneFor } from "../components/Ui";
import type { ConnectionConfig } from "../types";

const ENTITIES = [{ id: "partners", label: "Clientes e fornecedores" }, { id: "categories", label: "Categorias" }, { id: "departments", label: "Departamentos" }, { id: "projects", label: "Projetos" }];
type Bootstrap = { requirements: Array<{ name: string; configured: boolean; detail: string }>; configurations: ConnectionConfig[] };

export function SyncPage() {
  const { http } = useOonApi(); const [data, setData] = useState<Bootstrap | null>(null); const [connectionId, setConnectionId] = useState(""); const [entities, setEntities] = useState(ENTITIES.map(item => item.id)); const [sampleSize, setSampleSize] = useState(50); const [busy, setBusy] = useState(""); const [notice, setNotice] = useState<{ tone: "success" | "error" | "info"; text: string } | null>(null);
  const load = useCallback(async () => setData((await http.get<Bootstrap>("/cadastros/bootstrap")).data), [http]); useEffect(() => { void load().catch(reason => setNotice({ tone: "error", text: errorMessage(reason) })); }, [load]);
  async function save(event: FormEvent) { event.preventDefault(); setBusy("save"); try { await http.put("/cadastros/bootstrap", { connectionId, entities, sampleSize }); await load(); setNotice({ tone: "success", text: "Base adicionada à sincronização." }); } catch (reason) { setNotice({ tone: "error", text: errorMessage(reason) }); } finally { setBusy(""); } }
  async function run(id: string) { setBusy(id); try { const result = (await http.post<{ summary: string; correlationId: string }>("/cadastros/sync/run", { connectionId: id })).data; await load(); setNotice({ tone: "success", text: `${result.summary}. Protocolo ${result.correlationId}.` }); } catch (reason) { setNotice({ tone: "error", text: errorMessage(reason) }); } finally { setBusy(""); } }
  return <Page eyebrow="Central de sincronização" title="Controle explícito por base" description="Cadastros são lidos em páginas completas; o Omie permanece como fonte de verdade e cada execução gera protocolo.">
    {notice && <Notice tone={notice.tone}>{notice.text}</Notice>}
    <div className="oon-grid"><Card className="oon-span-8" title="Bases configuradas" description="Execute uma atualização completa quando precisar.">{!data?.configurations.length ? <Empty title="Nenhuma base configurada" description="Use o formulário ao lado para começar." /> : <div className="oon-list">{data.configurations.map(row => <article className="oon-list-item" key={row.connectionId}><div><strong>{row.connectionId}</strong><small>{row.entities.join(" • ")}</small></div><Badge tone={toneFor(row.lastSyncOutcome)}>{row.lastSyncOutcome}</Badge><div><small>Última execução</small><strong>{row.lastSyncAt ? new Date(row.lastSyncAt).toLocaleString("pt-BR") : "Nunca"}</strong></div><Button busy={busy === row.connectionId} onClick={() => run(row.connectionId)}>Sincronizar</Button></article>)}</div>}</Card>
    <Card className="oon-span-4" title="Adicionar base" description="Use o ID criado em Configurações Omie."><form onSubmit={save}><Field label="ID da conexão"><input required value={connectionId} onChange={event => setConnectionId(event.target.value)} placeholder="omie-matriz" /></Field><Field label="Registros por página"><input type="number" min={1} max={100} value={sampleSize} onChange={event => setSampleSize(Number(event.target.value))} /></Field><div className="oon-checks">{ENTITIES.map(item => <label className="oon-check" key={item.id}><input type="checkbox" checked={entities.includes(item.id)} onChange={event => setEntities(current => event.target.checked ? [...current, item.id] : current.filter(id => id !== item.id))} /> {item.label}</label>)}</div><Button type="submit" busy={busy === "save"} disabled={!entities.length}>Adicionar base</Button></form></Card></div>
    <Card title="Pré-requisitos do ambiente"><div className="oon-checks">{data?.requirements.map(item => <article className="oon-check" key={item.name}><Badge tone={item.configured ? "success" : "danger"}>{item.configured ? "Configurado" : "Pendente"}</Badge><strong>{item.name}</strong><p>{item.detail}</p></article>)}</div></Card>
  </Page>;
}
